version: '3.9'
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html  
    depends_on:
      - mysql-db  

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot  
    ports:
      - "80:80"
      - "443:443" 
    depends_on:
      - php-fpm  
      - mysql-db
 
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email tymc4enko17@gmail.com -d globus-studio.fun --agree-tos

        
  
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: orders
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db 
    ports:
      - "8081:80" 
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: password 
